[package]
name = "libmonsterengine"
version = "0.1.0"
authors = ["Shogo Otake <shogo.otake@gmail.com>"]
edition = "2018"

[lib]
name = "monsterengine"
crate-type = ["cdylib"]

[dependencies]
hyper = "0.12.20"
plamo = { path = "../plamo-rs" }
